ブランチを作り直した
Kimi0924/kimi-frontend-basic-last-assaignment pull request #3
Opened 2023-03-19 06:11 UTC by Kimi0924

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-03-31 13:29 UTC, caramelribon reviewed
コメントしました！

2023-03-31 13:29 UTC, caramelribon commented on src/components/molecules/card/card.html
> +  <div class="card-body">
card-bodyにデフォルトで18pxのpaddingがついてしまっているので、それをなくしましょう！

2023-03-31 13:29 UTC, caramelribon commented on src/components/molecules/card/card.scss
> +  margin: 37px 32px;
テキストとcard-buttonの間のmarginは.textかcard-buttonのどちらかで設定しましょう！
あと、値も異なっているので、figmaをもう一度見てみてください！

2023-03-31 13:29 UTC, caramelribon commented on src/components/molecules/card/card.scss
> +  margin-bottom: 32.73px;
こちら不要です！写真をhoverしたときに、拡大はするんですが、写真の表示範囲は変化しないので！

2023-03-31 13:29 UTC, caramelribon commented on src/components/molecules/card/card.scss
> +    transform: scale(1.1);
hoverを当てたときに、なめらかに変化するようにしましょう！atoms/buttonでも同じようなサービスでは実装していると思います！

2023-04-01 12:28 UTC, Kimi0924 commented on src/components/molecules/card/card.scss
> +  margin: 37px 32px;
textのmarginに反映させました！

2023-04-01 12:43 UTC, Kimi0924 commented on src/components/molecules/card/card.html
> +  <div class="card-body">
padding: initialで対応しました！

2023-04-01 12:46 UTC, Kimi0924 commented on src/components/molecules/card/card.html
> +  <div class="card-body">
padding: initialで対応しました！

質問：
デフォルトでpaddingが付いているかどうかはどのように確認すれば良いのですか？

2023-04-01 13:47 UTC, Kimi0924 commented on src/components/molecules/card/card.scss
> +  margin-bottom: 32.73px;
margin-bottomを消去しました。

質問：
margin-bottomを固定する方がhoverした際にも、表示範囲を固定できるのかと考えていましたがそういう仕組みではないのですね、、

2023-04-01 14:04 UTC, Kimi0924 commented on src/components/molecules/card/card.scss
> +    transform: scale(1.1);
transitionを入れました！

2023-04-02 15:23 UTC, caramelribon commented on src/components/molecules/card/card.html
> +  <div class="card-body">
レイアウトがどの様になっているか確認するためには、開発者ツールというものを使います！
こちらが資料です！
https://playground.wraptas.site/67db90c0263c44d58b966b5f23f69917

こちらの資料に書いてあるんですが、Elementsというところで、レイアウトを見たい要素を選択したあと、下か横に出ているタブの中のStylesというところを見ると、その要素がどのようなスタイルが当てられているかを見ることができます！

2023-04-02 15:31 UTC, caramelribon commented on src/components/molecules/card/card.scss
> +  margin-bottom: 32.73px;
marginは余白なので、hoverしていないときも、したときも写真の下に余白がついている状態になるだけです！
今回の場合、写真を拡大したときに、写真がCardの中には収まるようにしたいはずです！
そのために、overflow: hidden;を指定していると思います！
こちらは、ある要素内に収まらなかったときに、その部分を隠す(hidden)ために用います！
試しに、overflow: hidden;をはずすとこうなっています！

![スクリーンショット 2023-04-03 0 29 41](https://user-images.githubusercontent.com/91133956/229362835-0982181f-5c71-420b-8bfa-957ab9280ad2.png)

このはみ出た部分を隠すために、overflow: hidden;を使うという感じになります！

2023-04-03 06:35 UTC, MoAI522 commented on src/components/molecules/card/card.scss
> +.card-img-top {
このコンポーネントのスタイルが、意図せず他のコンポーネントに適用されてしまうことを防ぐために、スタイルは全て`.card`の中に入れ子にして書きましょう。
こんな感じ
```scss
.card {
  .card-img-top {
    ...
  }

  .card-img {
    ...
  }

  ...
}

2023-04-10 02:23 UTC, higashiji2000 requested changes
transitionの修正お願いします！

2023-04-10 02:23 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +    }
```suggestion
  .card-img-top {
    position: relative;
    transition: 0.2s ease;
    &:hover {
      overflow: hidden;
      transform: scale(1.1);
    }
```
transitionをhover擬似クラスに対して指定してしまうと、カーソルを話したときにtransitionが適用されません。
上のように修正お願いします！

2023-04-10 02:23 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +  }
```suggestion
  .card-body {
    padding: initial;
    padding: 32px;
  }

  .card-imgframe {
    z-index: 9;
    position: absolute;
    top: 0;
    border-bottom: 150px solid transparent;
    border-left: 150px solid $white;
  }

  .title {
    position: absolute;
    margin: 0px 6px;
    z-index: 10;
    top: 0px;
    left: 6px;
    color: $orange_bistre;
    font-size: $fontsize-l;
  }

  .text {
    font-size: $fontsize-s;
  }

  .card-button {
    display: flex;
    justify-content: center;
    line-height: 33.4px;
  }
```
現状でも全く問題ありませんが、今回のような余白の場合、子要素にmarginを設定するのではなく親要素( `card-body` )にpaddingを設定したほうがスッキリ書けるのでおすすめです。

2023-04-26 04:41 UTC, higashiji2000 approved these changes
LGTMです🎊

2023-04-28 01:16 UTC, merged